architecture: standalone

auth:
  enablePostgresUser: true
  username: "blackdaber"
  database: "grandlabs_dev"
  existingSecret: "postgres-secret"
  secretKeys:
    adminPasswordKey: "postgres-password"
    userPasswordKey: "password"

primary:
  persistence:
    enabled: true
    size: 2Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi