spring:
  config:
    import: vault://
  cloud:
    vault:
      uri: ${VAULT_ADDR}
      authentication: approle
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
      fail-fast: true
      kv:
        enabled: true
        backend: secret
        default-context: buggy-service/test
        application-name: ""
        profiles: ""

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:pg.grandlabs.dev}:${POSTGRES_PORT:5432}/${POSTGRES_DB:grandlabs_dev}
    username: <in vault>
    password: <in vault>
    hikari:
      max-lifetime: 1800000

logging:
  level:
    org.springframework.cloud.*: DEBUG
    ru.grandlabs.*: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.web.context: DEBUG
    org.springframework.session: DEBUG
  appender:
    name: CONSOLE
