spring:
  config:
    import: vault://
  cloud:
    vault:
      uri: ${VAULT_ADDR}
      authentication: approle
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
      ssl:
        trust-store: ${VAULT_SSL_TRUST_STORE}
        trust-store-password: ${VAULT_SSL_TRUST_STORE_PASSWORD}
        trust-store-type: PKCS12
      fail-fast: true
      kv:
        enabled: true
        backend: secret
        default-context: buggy-service/dev
        application-name: ""
        profiles: ""

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:pg.grandlabs.dev}:${POSTGRES_PORT:5432}/${POSTGRES_DB:grandlabs_dev}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}

logging:
  level:
    org.springframework.cloud.*: DEBUG
    ru.grandlabs.*: DEBUG
  appender:
    name: CONSOLE
