spring:
  config:
    import: vault://
  cloud:
    vault:
      uri: http://127.0.0.1:8200
      authentication: approle
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
      fail-fast: true
      kv:
        enabled: true
        backend: secret
        default-context: buggy-service/dev
        application-name: ""
        profiles: ""

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:127.0.0.1}:${POSTGRES_PORT:5432}/${POSTGRES_DB:grandlabs_dev}
    username: <in vault>
    password: <in vault>

logging:
  level:
    org.springframework.cloud.*: DEBUG
    ru.grandlabs.*: DEBUG
  appender:
    name: CONSOLE
